// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDvdoM0PPjP_Fx_q0QxAQq9_Vjeu27SA',
    appId: '1:229234619123:web:b650010ff5ed499dccbd86',
    messagingSenderId: '229234619123',
    projectId: 'music-app-49d70',
    authDomain: 'music-app-49d70.firebaseapp.com',
    storageBucket: 'music-app-49d70.firebasestorage.app',
    measurementId: 'G-71DQQ1YB2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiRgB3QbDLQhJ_QcrnhiM9ypLD_P7WLHo',
    appId: '1:229234619123:android:26acce3746929963ccbd86',
    messagingSenderId: '229234619123',
    projectId: 'music-app-49d70',
    storageBucket: 'music-app-49d70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUDxCy3FLFmU6-jIl0rsU0uaSW84Sbu9A',
    appId: '1:229234619123:ios:054598dec6963ef8ccbd86',
    messagingSenderId: '229234619123',
    projectId: 'music-app-49d70',
    storageBucket: 'music-app-49d70.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUDxCy3FLFmU6-jIl0rsU0uaSW84Sbu9A',
    appId: '1:229234619123:ios:054598dec6963ef8ccbd86',
    messagingSenderId: '229234619123',
    projectId: 'music-app-49d70',
    storageBucket: 'music-app-49d70.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiDvdoM0PPjP_Fx_q0QxAQq9_Vjeu27SA',
    appId: '1:229234619123:web:968a4b621160f4e5ccbd86',
    messagingSenderId: '229234619123',
    projectId: 'music-app-49d70',
    authDomain: 'music-app-49d70.firebaseapp.com',
    storageBucket: 'music-app-49d70.firebasestorage.app',
    measurementId: 'G-B1W4BKMVM3',
  );
}
